const PRODUCTS = [
  { id: 1, name: "Cono Helado", brand: "Val cream", price: 1200, category: "Impulsivos", presentation: "Unidad" },
  { id: 2, name: "Cono Helado", brand: "May cream", price: 1100, category: "Impulsivos", presentation: "Unidad" },
  { id: 3, name: "Bombón Helado", brand: "Val cream", price: 1000, category: "Impulsivos", presentation: "Unidad" },
  { id: 4, name: "Bombón Helado", brand: "May cream", price: 950, category: "Impulsivos", presentation: "Unidad" },
  { id: 5, name: "Bombón Crocante", brand: "Val cream", price: 1300, category: "Impulsivos", presentation: "Unidad" },
  { id: 6, name: "Bombón Crocante", brand: "May cream", price: 1200, category: "Impulsivos", presentation: "Unidad" },
  { id: 7, name: "Bombón Split", brand: "May cream", price: 1250, category: "Impulsivos", presentation: "Unidad" },
  { id: 9, name: "Pote 360cc", brand: "May cream", price: 2000, category: "Hogar", presentation: "360 cc" },
  { id: 10, name: "Pote 1400cc", brand: "May cream", price: 4500, category: "Hogar", presentation: "1.4 Litros" },
  { id: 11, name: "Pote 3 Litros", brand: "May cream", price: 8000, category: "Hogar", presentation: "3 Litros" },
  { id: 12, name: "Carita", brand: "May cream", price: 800, category: "Infantil", presentation: "Unidad" },
  { id: 13, name: "Alfabom", brand: "May cream", price: 1100, category: "Impulsivos", presentation: "Unidad" },
  { id: 14, name: "Rulito", brand: "May cream", price: 750, category: "Infantil", presentation: "Unidad" },
  { id: 15, name: "Cassata", brand: "May cream", price: 1500, category: "Postres", presentation: "Unidad" },
  { id: 16, name: "Palito de Agua", brand: "May cream", price: 500, category: "Impulsivos", presentation: "Unidad" },
  { id: 17, name: "Palito de Crema", brand: "May cream", price: 700, category: "Impulsivos", presentation: "Unidad" },
  { id: 18, name: "Torneado", brand: "May cream", price: 850, category: "Impulsivos", presentation: "Unidad" },
  { id: 19, name: "Copón", brand: "May cream", price: 1600, category: "Postres", presentation: "Unidad" },
  { id: 23, name: "Palito de Agua", brand: "Val cream", price: 550, category: "Impulsivos", presentation: "Unidad" },
  { id: 25, name: "Balde 5 Litros", brand: "May cream", price: 12000, category: "Baldes", presentation: "5 Litros" }
];
