const PRODUCTS = [
{id:1, name:"Cono", brand:"Val Cream", category:"Conos", presentation:"Caja x12 unidades", price:14600, emoji:"🍦"},
{id:2, name:"Cono", brand:"May Cream", category:"Conos", presentation:"Caja x12 unidades", price:13650, emoji:"🍦"},
{id:3, name:"Bombón", brand:"Val Cream", category:"Bombones", presentation:"Caja x24 unidades", price:14200, emoji:"🍫"},
{id:4, name:"Bombón", brand:"May Cream", category:"Bombones", presentation:"Caja x30 unidades", price:13650, emoji:"🍫"},
{id:5, name:"Bombón Crocante", brand:"Val Cream", category:"Bombones", presentation:"Caja x24 unidades", price:14200, emoji:"🍫"},
{id:6, name:"Bombón Crocante", brand:"May Cream", category:"Bombones", presentation:"Caja x27 unidades", price:13650, emoji:"🍫"},
{id:7, name:"Bombón Split", brand:"Val Cream", category:"Bombones", presentation:"Consultar WhatsApp", price:0, emoji:"🍫"},
{id:8, name:"Pote 360 cc", brand:"Val Cream", category:"Potes", presentation:"", price:0, emoji:"🍨"},
{id:9, name:"Pote 360 cc", brand:"May Cream", category:"Potes", presentation:"Pack x12 unidades", price:12300, emoji:"🍨"},
{id:10, name:"Pote 1400 cc", brand:"May Cream", category:"Potes", presentation:"La unidad", price:3500, emoji:"🍨"},
{id:11, name:"Balde 3 litros", brand:"May Cream", category:"Potes", presentation:"La unidad", price:8000, emoji:"🍨"},
{id:12, name:"Carita", brand:"May Cream", category:"Especiales", presentation:"", price:0, emoji:"😊"},
{id:13, name:"Alfabom", brand:"May Cream", category:"Especiales", presentation:"Caja x18 unidades", price:11700, emoji:"🍦"},
{id:14, name:"Rulo Relleno", brand:"May Cream", category:"Especiales", presentation:"", price:0, emoji:"🍦"},
{id:15, name:"Cassata", brand:"May Cream", category:"Especiales", presentation:"Caja x12 unidades", price:14500, emoji:"🍨"},
{id:16, name:"Palito Helado de Agua", brand:"May Cream", category:"Palitos", presentation:"Caja x40 unidades", price:5200, emoji:"🍭"},
{id:17, name:"Crema", brand:"May Cream", category:"Potes", presentation:"Caja x30 unidades", price:8200, emoji:"🍦"},
{id:18, name:"Torneado Doble", brand:"May Cream", category:"Especiales", presentation:"Caja x24 unidades", price:5750, emoji:"🍦"},
{id:19, name:"Copón", brand:"May Cream", category:"Especiales", presentation:"Caja x12 unidades", price:17500, emoji:"🍨"},
{id:20, name:"Bombón Corazón", brand:"May Cream", category:"Bombones", presentation:"", price:0, emoji:"❤️"},
{id:21, name:"Granizados", brand:"May Cream", category:"Especiales", presentation:"", price:0, emoji:"🍫"},
{id:22, name:"Alfabom", brand:"Val-Cream", category:"Especiales", presentation:"", price:0, emoji:"🍦"},
{id:23, name:"Palito Helado de Agua", brand:"Val-Cream", category:"Palitos", presentation:"Caja x36 unidades", price:6000, emoji:"🍭"},
{id:24, name:"Latidos", brand:"Val-Cream", category:"Especiales", presentation:"", price:0, emoji:"❤️"},
{id:25, name:"Balde 5 litros", brand:"May Cream", category:"Potes", presentation:"La unidad", price:11000, emoji:"🍨"},
];
